# Generated by Django 5.2.7 on 2025-10-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('watering_frequency', models.CharField(max_length=100)),
                ('sunlight', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
