# Generated by Django 5.2.7 on 2025-10-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_favorite_user_schedule_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
