# Generated by Django 5.2.7 on 2025-10-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_plant_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering_frequency',
            field=models.TextField(),
        ),
    ]
