# Generated by Django 5.2.7 on 2025-11-03 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_favorite_note_userplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_plants', to='main_app.category'),
        ),
    ]
