# Generated by Django 5.2.7 on 2025-11-03 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_userplant_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='note',
        ),
    ]
