# Generated by Django 5.2.7 on 2025-11-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_schedule_note_alter_schedule_plant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
