# Generated by Django 5.2.7 on 2025-11-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplant',
            name='type',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=20, null=True),
        ),
    ]
