# Generated by Django 5.2.7 on 2025-11-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_userplant_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPlant',
        ),
    ]
